CREATE TABLE IF NOT EXISTS air_quality (
 id SERIAL PRIMARY KEY, timestamp_local TIMESTAMP NOT NULL, aqi INTEGER NOT NULL, pm25 DOUBLE PRECISION, pm10 DOUBLE PRECISION, o3 DOUBLE PRECISION, no2 DOUBLE PRECISION, so2 DOUBLE PRECISION, co DOUBLE PRECISION, pm10_pm25_ratio DOUBLE PRECISION, year INTEGER, month INTEGER, day INTEGER, hour INTEGER, city_name VARCHAR(100), country_code VARCHAR(10), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_air_quality_timestamp ON air_quality(timestamp_local);
